---
kind: pipeline
type: ssh
name: default

server:
  host: 35.74.237.19
  username:
      from_secret: docker_username
  password:
    from_secret: docker_password

steps:
- name: greeting
  commands:
  - echo hello world

...


