---
---
kind: pipeline
type: ssh
name: default

server:
  host: 1.2.3.4
  username:
      from_secret: docker_username
  password:
    from_secret: docker_password

steps:
- name: greeting
  commands:
  - echo hello world

...


