---
kind: pipeline
type: ssh
name: default

server:
  host: 
    from_secret: 1.2.3.4
  user: 
    from_secret: username
  password:
    from_secret: password

steps:
- name: greeting
  commands:
  - echo hello world

...
