---
kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: 7UG4p7MXx76YRPKeIGwNrjEqMJMFGA59gPBq/b3QxxApHjnZH8oRLhj91A==



